// Research dossier deck: one completed quest + its report in, ONE complete
// self-contained projector-ready HTML slideshow out — inline CSS, a small
// inline deck controller, no external assets. Modeled on the pitch-deck
// template (src/slideshow/template.ts): every model/user-influenced string is
// escaped HERE; the only raw injection is the QR SVG, which this server
// generates itself from the (validated http/https) source URL.
//
// Slides: 1. the claim as heard · 2. findings with verdicts · 3. bias &
// blind spots · 4. sources with scan-me QR codes · 5. keep digging.

import { escapeHtml } from "../slideshow/template";
import type { ResearchQuest, ResearchReport, ResearchVerdict } from "./types";

// One source prepared for rendering: the report source + its QR SVG (already
// generated by the caller via src/publish/qr.ts — the deck stays sync + pure).
export interface DeckSource {
  title: string;
  url: string;
  publisher: string;
  note: string;
  qrSvg: string;
}

export interface ResearchDeckInput {
  quest: ResearchQuest;
  report: ResearchReport;
  sources: readonly DeckSource[];
}

const VERDICT_LABEL: Record<ResearchVerdict, string> = {
  supported: "SUPPORTED",
  refuted: "REFUTED",
  mixed: "MIXED",
  unverified: "UNVERIFIED",
};

export function renderResearchDeckHtml(input: ResearchDeckInput): string {
  const { quest, report } = input;
  const slides = [
    heroSlide(quest, report),
    findingsSlide(report),
    biasSlide(report),
    sourcesSlide(input.sources),
    followUpSlide(report),
  ];
  const title = `${quest.topic} — research`;
  const footer = `${quest.id} · ${quest.kind} · vibersyn research`;
  return [
    "<!doctype html>",
    '<html lang="en">',
    "<head>",
    '<meta charset="utf-8" />',
    '<meta name="viewport" content="width=device-width, initial-scale=1" />',
    `<title>${escapeHtml(title)}</title>`,
    `<style>${DECK_CSS}</style>`,
    "</head>",
    "<body>",
    '<main class="deck" data-deck>',
    slides
      .map(
        (slide, index) =>
          `<section class="slide${index === 0 ? " active" : ""}" data-slide="${index}">${slide}</section>`,
      )
      .join("\n"),
    "</main>",
    '<nav class="deck-nav">',
    '<button type="button" class="nav-btn" data-nav="prev" data-dwell="deck-prev" aria-label="Previous slide">‹</button>',
    `<div class="dots">${slides.map((_, index) => `<button type="button" class="dot${index === 0 ? " active" : ""}" data-dot="${index}" data-dwell="deck-dot-${index}" aria-label="Slide ${index + 1}"></button>`).join("")}</div>`,
    '<button type="button" class="nav-btn" data-nav="next" data-dwell="deck-next" aria-label="Next slide">›</button>',
    "</nav>",
    `<footer class="deck-footer">${escapeHtml(footer)}</footer>`,
    `<script>${DECK_JS}</script>`,
    "</body>",
    "</html>",
  ].join("\n");
}

function heroSlide(quest: ResearchQuest, report: ResearchReport): string {
  const heard =
    quest.contextSpan.quote.trim().length > 0
      ? `<p class="heard">Heard in the room: <q>${escapeHtml(quest.contextSpan.quote)}</q></p>`
      : "";
  return [
    `<span class="kicker">Researched from the room · ${escapeHtml(quest.kind)}</span>`,
    `<h1>${escapeHtml(quest.topic)}</h1>`,
    `<blockquote class="claim">${escapeHtml(quest.claim)}</blockquote>`,
    heard,
    `<p class="confidence conf-${escapeHtml(report.confidence)}">research confidence: ${escapeHtml(report.confidence)}</p>`,
  ].join("\n");
}

function findingsSlide(report: ResearchReport): string {
  const findings =
    report.findings.length === 0
      ? '<p class="empty">No discrete findings — see the summary above.</p>'
      : `<ul class="findings">${report.findings
          .map(
            (finding) =>
              `<li class="finding"><span class="verdict verdict-${escapeHtml(finding.verdict)}">${VERDICT_LABEL[finding.verdict]}</span>` +
              `<div class="finding-body"><p class="finding-claim">${escapeHtml(finding.claim)}</p>` +
              (finding.explanation.length > 0 ? `<p class="finding-why">${escapeHtml(finding.explanation)}</p>` : "") +
              (finding.sourceIndexes.length > 0
                ? `<p class="finding-src">sources ${finding.sourceIndexes.map((index) => `#${index + 1}`).join(", ")}</p>`
                : "") +
              "</div></li>",
          )
          .join("")}</ul>`;
  return [
    '<span class="kicker">What we found</span>',
    "<h1>Findings, fact-checked</h1>",
    `<p class="summary">${escapeHtml(report.summary)}</p>`,
    findings,
  ].join("\n");
}

function biasSlide(report: ResearchReport): string {
  const notes =
    report.biasNotes.length === 0
      ? '<p class="empty">No significant bias signals were flagged — stay skeptical anyway.</p>'
      : `<ul class="bias-notes">${report.biasNotes
          .map(
            (note) =>
              `<li class="bias-note"><span class="severity severity-${escapeHtml(note.severity)}">${escapeHtml(note.severity)}</span>` +
              `<p>${escapeHtml(note.note)}</p></li>`,
          )
          .join("")}</ul>`;
  return ['<span class="kicker">Read with care</span>', "<h1>Bias &amp; blind spots</h1>", notes].join("\n");
}

function sourcesSlide(sources: readonly DeckSource[]): string {
  const cards =
    sources.length === 0
      ? '<p class="empty">No live sources were captured for this quest.</p>'
      : `<div class="sources">${sources
          .map(
            (source, index) =>
              '<article class="source-card">' +
              `<div class="source-qr" aria-label="QR code for ${escapeHtml(source.url)}">${source.qrSvg}</div>` +
              `<div class="source-meta"><span class="source-index">#${index + 1}</span>` +
              `<h2>${escapeHtml(source.title)}</h2>` +
              (source.publisher.length > 0 ? `<p class="source-pub">${escapeHtml(source.publisher)}</p>` : "") +
              (source.note.length > 0 ? `<p class="source-note">${escapeHtml(source.note)}</p>` : "") +
              `<p class="source-url">${escapeHtml(source.url)}</p></div></article>`,
          )
          .join("")}</div>`;
  return ['<span class="kicker">Scan to read</span>', "<h1>Sources</h1>", cards].join("\n");
}

function followUpSlide(report: ResearchReport): string {
  const items =
    report.followUps.length === 0
      ? '<p class="empty">Nothing queued — the room decides where to dig next.</p>'
      : `<ul class="followups">${report.followUps.map((item) => `<li>${escapeHtml(item)}</li>`).join("")}</ul>`;
  return ['<span class="kicker">Keep digging</span>', "<h1>Open questions</h1>", items].join("\n");
}

// House palette + type (matches src/ui/styles.css "The Deep"). Verdict colors
// reuse the fixed status semantics: supported=active green, refuted=halted
// red, mixed=paused amber, unverified=faint ink. Violet never signals state.
const DECK_CSS = `
:root { color-scheme: dark; }
* { box-sizing: border-box; }
body {
  margin: 0; min-height: 100vh; display: flex; flex-direction: column;
  background: radial-gradient(120% 120% at 50% 0%, #0a1a26 0%, #05070d 70%);
  color: #e8f2f5; font: 16px/1.5 "Inter", ui-sans-serif, system-ui, -apple-system, sans-serif;
}
.deck { flex: 1; position: relative; }
.slide {
  position: absolute; inset: 0; display: none; flex-direction: column; justify-content: center;
  padding: 6vh 8vw; overflow: auto;
}
.slide.active { display: flex; }
.kicker { color: #00bcd4; text-transform: uppercase; letter-spacing: 0.14em; font-size: 14px; font-weight: 600; }
h1 { font-size: clamp(30px, 5vw, 54px); margin: 0.25em 0 0.5em; line-height: 1.12; }
.claim { margin: 0; padding: 18px 24px; border-left: 3px solid #00bcd4; background: rgba(16,30,40,0.5);
  font-size: clamp(20px, 2.6vw, 30px); border-radius: 0 12px 12px 0; }
.heard { color: #aebfc8; font-size: 17px; }
.confidence { font-weight: 700; text-transform: uppercase; letter-spacing: 0.1em; font-size: 14px; }
.conf-high { color: #00ff88; } .conf-medium { color: #f5a623; } .conf-low { color: #8aa0ab; }
.summary { max-width: 68ch; color: #cfe0e8; font-size: clamp(17px, 1.7vw, 21px); }
.findings, .bias-notes, .followups { list-style: none; margin: 0; padding: 0; display: grid; gap: 14px; }
.finding, .bias-note { display: flex; gap: 16px; align-items: flex-start; background: rgba(16,30,40,0.42);
  border: 1px solid rgba(150,200,220,0.14); border-radius: 14px; padding: 16px 18px; }
.verdict, .severity { flex: 0 0 auto; font-weight: 800; font-size: 12px; letter-spacing: 0.1em;
  padding: 5px 10px; border-radius: 999px; border: 1px solid currentColor; }
.verdict-supported { color: #00ff88; } .verdict-refuted { color: #ff3b30; }
.verdict-mixed { color: #f5a623; } .verdict-unverified { color: #8aa0ab; }
.severity-low { color: #8aa0ab; } .severity-medium { color: #f5a623; } .severity-high { color: #ff3b30; }
.finding-body p, .bias-note p { margin: 0 0 6px; }
.finding-claim { font-weight: 600; font-size: 18px; }
.finding-why { color: #aebfc8; }
.finding-src { color: #8aa0ab; font-size: 13px; }
.sources { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 18px; }
.source-card { display: flex; gap: 16px; background: rgba(16,30,40,0.42); border: 1px solid rgba(150,200,220,0.14);
  border-radius: 14px; padding: 16px; }
.source-qr { flex: 0 0 128px; background: #fff; border-radius: 10px; padding: 8px; }
.source-qr svg { display: block; width: 100%; height: auto; }
.source-meta h2 { margin: 2px 0 4px; font-size: 18px; line-height: 1.25; }
.source-index { color: #00bcd4; font-weight: 700; font-size: 13px; }
.source-pub { color: #9affc9; margin: 0 0 4px; font-size: 14px; }
.source-note { color: #aebfc8; margin: 0 0 6px; font-size: 14px; }
.source-url { color: #8aa0ab; margin: 0; font-size: 12px; word-break: break-all;
  font-family: "SFMono-Regular", Consolas, monospace; }
.followups li { background: rgba(16,30,40,0.42); border: 1px solid rgba(150,200,220,0.14);
  border-radius: 14px; padding: 14px 18px; font-size: 18px; }
.empty { color: #8aa0ab; font-style: italic; }
.deck-nav { display: flex; align-items: center; justify-content: center; gap: 18px; padding: 10px 0 6px; }
.nav-btn { background: rgba(16,30,40,0.6); color: #e8f2f5; border: 1px solid rgba(150,200,220,0.2);
  border-radius: 10px; font-size: 24px; line-height: 1; padding: 8px 20px; cursor: pointer; }
.nav-btn:hover { border-color: #00bcd4; }
.dots { display: flex; gap: 10px; }
.dot { width: 12px; height: 12px; border-radius: 50%; border: 1px solid rgba(150,200,220,0.4);
  background: transparent; cursor: pointer; padding: 0; }
.dot.active { background: #00bcd4; border-color: #00bcd4; }
.deck-footer { text-align: center; color: #8aa0ab; font-size: 12px; padding: 4px 0 12px;
  font-family: "SFMono-Regular", Consolas, monospace; }
`;

// Tiny deck controller: prev/next/dot buttons (all plain <button data-dwell>,
// so the gesture wall's dwell selector drives them) + arrow-key navigation.
const DECK_JS = `
(function () {
  var slides = Array.prototype.slice.call(document.querySelectorAll("[data-slide]"));
  var dots = Array.prototype.slice.call(document.querySelectorAll("[data-dot]"));
  var current = 0;
  function show(index) {
    current = (index + slides.length) % slides.length;
    slides.forEach(function (slide, i) { slide.classList.toggle("active", i === current); });
    dots.forEach(function (dot, i) { dot.classList.toggle("active", i === current); });
  }
  document.querySelectorAll("[data-nav]").forEach(function (button) {
    button.addEventListener("click", function () {
      show(current + (button.getAttribute("data-nav") === "next" ? 1 : -1));
    });
  });
  dots.forEach(function (dot, i) { dot.addEventListener("click", function () { show(i); }); });
  document.addEventListener("keydown", function (event) {
    if (event.key === "ArrowRight" || event.key === " ") show(current + 1);
    if (event.key === "ArrowLeft") show(current - 1);
  });
})();
`;
